### ISSUE TITLE
README needs to be updated with new "libunshield" repo

### ISSUE THREAD

**Issue by ILMostro** [kmdm/unruu#8]
Thanks so much for this...just wanted to point out that the configure script of "unruu" requires "libunshield" version 0.9 or greater; whereas the one in the given repo at "https://github.com/kmdm/unshield.git" is version 0.8

I've made it work with the github.com/twogood/unshield.git repo which is version 0.9

**Comment by kmdm** [comment]
Quite right, thanks! :)

(Committed again since that update poorly fixed it _sigh_... too much haste)

**Comment by ILMostro** [comment]
Awesome tool, thanks again...I'm pleasantly surprised at how quickly you responded to apply the fix.  Keep up the good work bro.
